examples/apps/django_multi_apps/django_multi_apps/urls.py
from bokeh.server.django import autoload, static_extensions
from django.apps import apps
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

import sliders.pn_app as sliders_app
import gbm.pn_app as gbm_app
import stockscreener.pn_app as stockscreener_app

from .themes import plot_themes

pn_app_config = apps.get_app_config('bokeh.server.django')

urlpatterns = [
    path('', include('landing.urls')),
    path('sliders/', include('sliders.urls')),
    path('gbm/', include('gbm.urls')),
    path('stockscreener/', include('stockscreener.urls')),
    path('admin/', admin.site.urls),
]

bokeh_apps = [
    autoload("sliders", sliders_app.app),
    autoload("gbm", gbm_app.app),
    autoload("stockscreener", stockscreener_app.app),
]

urlpatterns += static_extensions()
urlpatterns += staticfiles_urlpatterns()

# Set the themes
plot_themes()

examples/apps/django_multi_apps/gbm/urls.py
from django.urls import path

from . import views

app_name = 'gbm'
urlpatterns = [
    path('', views.gbm, name='gbm'),
]

examples/apps/django_multi_apps/landing/urls.py
from django.urls import path

from .views import landing

urlpatterns = [
    path('', landing, name='landing'),
]

examples/apps/django_multi_apps/sliders/urls.py
from django.urls import path

from . import views

app_name = 'sliders'
urlpatterns = [
    path('', views.sliders, name='sliders'),
]

examples/apps/django_multi_apps/stockscreener/urls.py
from django.urls import path

from . import views

app_name = 'stockscreener'
urlpatterns = [
    path('', views.stockscreener, name='stockscreener'),
]

examples/apps/django_multi_apps/gbm/models.py
from django.db import models

# Create your models here.

examples/apps/django_multi_apps/landing/models.py
from django.db import models

# Create your models here.

examples/apps/django_multi_apps/sliders/models.py
from django.db import models

# Create your models here.

examples/apps/django_multi_apps/stockscreener/models.py
from django.db import models

# Create your models here.

examples/apps/django_multi_apps/gbm/views.py
# Create your views here.
from bokeh.embed import server_document

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def gbm(request: HttpRequest) -> HttpResponse:
    script = server_document(request.build_absolute_uri())
    return render(request, "gbm/gbm.html", dict(script=script))

examples/apps/django_multi_apps/landing/views.py
from django.shortcuts import render

# Create your views here.
def landing(request):
    return render(request, "landing/landing.html")

examples/apps/django_multi_apps/sliders/views.py
# Create your views here.
from bokeh.embed import server_document

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def sliders(request: HttpRequest) -> HttpResponse:
    script = server_document(request.build_absolute_uri())
    return render(request, "sliders/sliders.html", dict(script=script))

examples/apps/django_multi_apps/stockscreener/views.py
# Create your views here.
from bokeh.embed import server_document

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def stockscreener(request: HttpRequest) -> HttpResponse:
    script = server_document(request.build_absolute_uri())
    return render(request, "stockscreener/stockscreener.html", dict(script=script))

examples/apps/django_multi_apps/templates/base.html
{% load static %}

{% block doc %}
    <!doctype html>
    <html lang="en">
    {% block html %}
        <head>
            {% block head %}
                <title>{% block title %}Django Panel{% endblock title %}</title>
                <!-- Required meta tags -->
                {% block meta %}
                    <meta charset="utf-8">
                    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
                    <meta name="description" content="Testing Website of the ZGL limited company">
                    <meta name="keywords" content="Prototype Website for Testing of new Technology, Keep out">
                {% endblock meta %}

                {% block styles %}
                    <!-- Bootstrap CSS -->
                    <link rel="stylesheet"
                          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
                          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
                          crossorigin="anonymous">
                {% endblock styles %}
                <link rel="shortcut icon" href="{% static 'icons/favicon32x32.png' %}" type="image/x-icon">
                <link rel="icon" href="{% static 'icons/favicon32x32.png' %}" type="image/x-icon">
            {% endblock head %}
        </head>

        <!-- BODY -->
        <body id="home"{% block body_attributs %}{% endblock body_attributs %}>
        {% block body %}
            <!-- NAVBAR -->
            {% block navbar %}
                {% if user.is_authenticated %}
                    <nav id="main-nav" class="navbar navbar-expand-md navbar-dark bg-blue fixed-top
                            {% block navbar_class %}{% endblock navbar_class %}">
                {% else %}
                    <nav id="main-nav" class="navbar navbar-expand-md navbar-dark bg-dark navbar-fixed-top">
                {% endif %}
            <div class="container-fluid">
                <!-- brand -->
                <a class="navbar-brand d-none d-sm-block logo" href="/">
                    [...@djangopanel ~]$<span class="blink_me">_</span></a>
                <a class="navbar-brand d-block d-sm-none logo"
                   href="/">[djangopanel ~]$<span
                        class=" blink_me">_</span></a>
                <!-- navigation button and toggler-icon -->
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- navbar collect element -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav ml-auto mr-4">
                        {% block navbar_item %}
                            <li class="nav-item">
                                <a href="{% url 'stockscreener:stockscreener' %}" class="nav-link">Stockscreener<span
                                        class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'sliders:sliders' %}" class="nav-link">Sliders<span
                                        class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'gbm:gbm' %}" class="nav-link">GBM<span
                                        class="sr-only">(current)</span></a>
                            </li>
                        {% endblock navbar_item %}
                    </ul>
                </div>
            </div>
            </nav>
            {% endblock navbar %}

            <!-- MAIN-->

            <!-- FLASH MESSAGES -->
            <div class="container">
                {% block messages %}
                    <div class="col-md-8">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times</span>
                                    </button>
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                {% endblock messages %}
            </div>
            <!-- CONTENT -->
            {% block content %}
                {{ server_script|safe }}
            {% endblock %}


            <!-- FOOTER -->
            {% if user.is_authenticated %}
                <footer id="footer" class="container-fluid bg-blue text-center p-2 fixed-bottom">
            {% else %}
                <footer id="footer" class="container-fluid bg-dark text-white text-center p-2 fixed-bottom">
            {% endif %}
        {% block footer %}
            Copyright &copy; <span class="year"></span> me
        {% endblock footer %}
        </footer>

            {% block scripts %}
                <script src="https://code.jquery.com/jquery-3.3.1.min.js"
                        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
                        crossorigin="anonymous"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
                        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
                        crossorigin="anonymous"></script>
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
                        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
                        crossorigin="anonymous"></script>

            {% endblock scripts %}
        {% endblock body %}
        </body>
    {% endblock html %}
    </html>
{% endblock doc %}

examples/apps/django_multi_apps/templates/gbm/gbm.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <div class="jumbotron jumbotron-fluid bg-primary text-center text-white">
        <h1>Geometric Metric Brownian Motion</h1>
        <p class="lead">Making Sense of the Noise</p>
    </div>

    <div class="container text-center">
        <div class="row">
            <div class="col-md-12">
                {{ script | safe }}
            </div>
        </div>
    </div>

{% endblock %}

examples/apps/django_multi_apps/templates/landing/landing.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <div class="jumbotron jumbotron-fluid bg-danger text-center">
        <h1>Landing Page</h1>
        <p class="lead">Predictive Analytics</p>
    </div>


{%  endblock content %}

examples/apps/django_multi_apps/templates/sliders/sliders.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="jumbotron jumbotron-fluid bg-success text-center">
        <h1>Sliders App</h1>
        <p class="lead">Panel Sinewave</p>
    </div>

    <div class="container-fluid text-center">
        <div class="row">
            <div class="col-md-6">
                <h1>This is App1 </h1>
                {{ script | safe }}
            </div>
            <div class="col-md-6">
                <h1>This is App2 </h1>
                {{ script | safe }}
            </div>
        </div>
    </div>

{%  endblock content %}

examples/apps/django_multi_apps/templates/stockscreener/stockscreener.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="jumbotron jumbotron-fluid bg-warning text-center">
        <h1>StockScreener</h1>
        <p class="lead">A look at the market</p>
    </div>

    <div class="container text-center">
        <div class="row">
            {{ script | safe }}
        </div>
    </div>

{% endblock content %}